# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41c0bb39f0d577431d473482d8288881202c876cdf7f838621bcff7d43fd8366702aebae2ab1c8174d8576a77a80c2855da0208f4b758f921c2312c171c94fce

test:
  secret_key_base: abeaf37c75ea69a026cd309aff7e94743b25fd068434070ef9202908d26f8a0b3b3b273d22392965a2b5ecdeb07f161eddbfb94e3961f4e7d4e63697fd68a943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
